### PR TITLE
Fixed AB#29

### PR DESCRIPTION
**Pull request by JoonaPeltola**
Fixed [AB#29](https://dev.azure.com/SoftwareDeliveryTools/42dd33bf-5496-40bc-93a2-b1a9597cdd60/_workitems/edit/29)

### CODE REVIEW

**Comment by V1ltzu** [comment]
nice work

**Review by V1ltzu — COMMENTED** [review]
ok nice

**Review by Tuomas-Talkio — APPROVED** [review]
Good Changes

**Review by V1ltzu — APPROVED** [review]
nice

**Pull request merged**
