### PR TITLE
KonstaH_branch1

### PR DESCRIPTION
**Pull request by konstahakli**
Fixes [AB#24](https://dev.azure.com/SoftwareDeliveryTools/42dd33bf-5496-40bc-93a2-b1a9597cdd60/_workitems/edit/24)

### CODE REVIEW

**Review by JoonaPeltola — CHANGES_REQUESTED** [review]
Fix typo

**Review by Tuomas-Talkio — CHANGES_REQUESTED** [review]
Fix typo

**Review by JoonaPeltola — APPROVED** [review]
Good job

**Review by Tuomas-Talkio — APPROVED** [review]
Good job fixing typo

**Pull request merged**
